/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerRequisicao;
import Model.Requisicao;
import com.google.gson.Gson;
import javax.swing.JOptionPane;


/**
 *
 * @author thiagorozaa
 */
public class TelaInclusao extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaInclusao() {
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumeroProcedimento = new javax.swing.JLabel();
        jLabelSexo = new javax.swing.JLabel();
        jLabelIdade = new javax.swing.JLabel();
        jTextFieldNumeroProcedimento = new javax.swing.JTextField();
        jTextFieldSexo = new javax.swing.JTextField();
        jTextFieldIdade = new javax.swing.JTextField();
        jButtonIncluir = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelCpf = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelNumeroProcedimento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroProcedimento.setText("Informe o número do procedimento:");
        getContentPane().add(jLabelNumeroProcedimento);
        jLabelNumeroProcedimento.setBounds(30, 140, 230, 16);

        jLabelSexo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSexo.setText("Informe o sexo:");
        getContentPane().add(jLabelSexo);
        jLabelSexo.setBounds(30, 190, 230, 16);

        jLabelIdade.setForeground(new java.awt.Color(255, 255, 255));
        jLabelIdade.setText("Informe sua idade:");
        getContentPane().add(jLabelIdade);
        jLabelIdade.setBounds(30, 240, 230, 16);
        getContentPane().add(jTextFieldNumeroProcedimento);
        jTextFieldNumeroProcedimento.setBounds(30, 160, 230, 30);
        getContentPane().add(jTextFieldSexo);
        jTextFieldSexo.setBounds(30, 210, 230, 30);
        getContentPane().add(jTextFieldIdade);
        jTextFieldIdade.setBounds(30, 260, 230, 30);

        jButtonIncluir.setText("Incluir");
        jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIncluirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIncluir);
        jButtonIncluir.setBounds(170, 360, 97, 29);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(0, 0, 480, 130);

        jLabelCpf.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCpf.setText("Informe seu CPF:");
        getContentPane().add(jLabelCpf);
        jLabelCpf.setBounds(30, 290, 230, 16);
        getContentPane().add(jTextFieldCpf);
        jTextFieldCpf.setBounds(30, 310, 230, 30);

        jLabelFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/asq.png"))); // NOI18N
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(0, 0, 800, 459);

        setSize(new java.awt.Dimension(697, 481));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
        // TODO add your handling code here:
        
        Requisicao req = new Requisicao();
        
        req.codigoProcedimento = Integer.parseInt(jTextFieldNumeroProcedimento.getText());
        req.idade              = Integer.parseInt(jTextFieldIdade.getText());
        req.sexo               = jTextFieldSexo.getText().charAt(0);
        req.cpf                = jTextFieldCpf.getText();

        //instancia um objeto da classe Gson
        Gson gson = new Gson();

        //Armazena em uma String os dados de uma requisição convertidos em formato Json
        String objetoJson = gson.toJson(req);

        //imprime os resultados
        //System.out.println(objetoJson);
        //JOptionPane.showMessageDialog(rootPane, objetoJson);
        
        if (req.validaRequisicao(objetoJson)){
            ControllerRequisicao cr = new ControllerRequisicao();
            cr.inserir(objetoJson);
        }
        
        
       
    }//GEN-LAST:event_jButtonIncluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInclusao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInclusao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonIncluir;
    private javax.swing.JLabel jLabelCpf;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelIdade;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNumeroProcedimento;
    private javax.swing.JLabel jLabelSexo;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldIdade;
    private javax.swing.JTextField jTextFieldNumeroProcedimento;
    private javax.swing.JTextField jTextFieldSexo;
    // End of variables declaration//GEN-END:variables
}
