/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ControllerRequisicao;
import javax.swing.JOptionPane;

/**
 *
 * @author thiagorozaa
 */
public class TelaConsultar extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaConsultar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNumeroProcedimento = new javax.swing.JLabel();
        jTextFieldNumeroProcedimento = new javax.swing.JTextField();
        jButtonPesquisar = new javax.swing.JButton();
        jLabelLogo = new javax.swing.JLabel();
        jLabelResultado = new javax.swing.JLabel();
        jLabelFundoTelaPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabelNumeroProcedimento.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroProcedimento.setText("Informe o número do procedimento:");
        getContentPane().add(jLabelNumeroProcedimento);
        jLabelNumeroProcedimento.setBounds(30, 140, 230, 16);
        getContentPane().add(jTextFieldNumeroProcedimento);
        jTextFieldNumeroProcedimento.setBounds(30, 160, 230, 30);

        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar);
        jButtonPesquisar.setBounds(260, 160, 97, 29);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/logo.png"))); // NOI18N
        getContentPane().add(jLabelLogo);
        jLabelLogo.setBounds(0, 0, 480, 130);
        getContentPane().add(jLabelResultado);
        jLabelResultado.setBounds(30, 200, 650, 230);

        jLabelFundoTelaPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/asq.png"))); // NOI18N
        getContentPane().add(jLabelFundoTelaPrincipal);
        jLabelFundoTelaPrincipal.setBounds(0, 0, 800, 459);

        setSize(new java.awt.Dimension(697, 481));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        // TODO add your handling code here:
        
        Integer numeroProcedimento = null;
        
        if ( (!jTextFieldNumeroProcedimento.getText().isEmpty()) ){ 
            //Busca procedimento no banco de dados 
            numeroProcedimento = Integer.parseInt(jTextFieldNumeroProcedimento.getText());
            
            ControllerRequisicao cr = new ControllerRequisicao();
            cr.consultar(numeroProcedimento);
            
        }
            
        
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaConsultar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JLabel jLabelFundoTelaPrincipal;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelNumeroProcedimento;
    private javax.swing.JLabel jLabelResultado;
    private javax.swing.JTextField jTextFieldNumeroProcedimento;
    // End of variables declaration//GEN-END:variables
}
